### PR TITLE
add dm_conversation_id to TDMEventV2Field

### PR DESCRIPTION
**Pull request by RenKoya1**
https://developer.x.com/en/docs/x-api/direct-messages/lookup/api-reference/get-dm_events

### CODE REVIEW

**Comment by PLhery** [comment]
Thank you! Actually the rest of the fields seem wrong, maybe you could try to fix that too?

**Comment by RenKoya1** [comment]
Okay!

**Comment by PLhery** [comment]
Hello,

I believed you added "texts" to BaseDMEventV2, but I don't think "ParticipantsJoin" events have text

What I meant is that the other TDMEventV2Field accepted strings seemed wrong to me, maybe I'm wrong

**Comment by RenKoya1** [comment]
Ye

> Hello,
> 
> I believed you added "texts" to BaseDMEventV2, but I don't think "ParticipantsJoin" events have text
> 
> What I meant is that the other TDMEventV2Field accepted strings seemed wrong to me, maybe I'm wrong

My bad. I fixed it

**Comment by PLhery** [comment]
thank you! (id, name, event type are missing too, I'll add them myself)

**Comment by PLhery** [comment]
Published in 1.18.2

**Pull request merged**
