### PR TITLE
update domain from twitter.com to x.com

### PR DESCRIPTION
**Pull request by melvinmcrn**
This PR is based on Elon's tweet: https://x.com/elonmusk/status/1791351500217754008

Please help review @PLhery

### CODE REVIEW

**Comment by PLhery** [comment]
Approved!

**Comment by PLhery** [comment]
I won't trigger a new version for now, as it's not really necessary, but thank you

**Comment by melvinmcrn** [comment]
@PLhery I'm using this lib for my app and would love if it could generate the Auth URL as x.com though so users won't need to redirect when authorizing my application.

**Comment by PLhery** [comment]
It makes sense, I will create a new version tonight!

**Comment by Dubzer** [comment]
looks like oauth 1 with x.com stopped working. "login" button on the https://api.x.com/oauth redirects to api.twitter.com, where I get the following error:

image

**Comment by PLhery** [comment]
Thank you, I'm reverting the commit

**Comment by PLhery** [comment]
Reverted in 1.17.1

**Comment by avoc-ado** [comment]
I upgraded to 1.71.0, and the oauth2 flow worked great on x.com :)

**Comment by PLhery** [comment]
Any second person could confirm this? Then I'd re-revert

**Comment by dylan1951** [comment]
Can confirm x.com works great for OAuth 2. Using twitter.com forces the user to login again.

**Comment by PLhery** [comment]
twitter.com -> x.com published again in 1.18.0

**Pull request merged**
