### PR TITLE
feat: get tweet usage v2

### PR DESCRIPTION
**Pull request by jiahuijiang**
Create API for /usage in v2 API.

API
https://developer.x.com/en/docs/x-api/usage/tweets/introduction

API params (not listed in their official doc, but in their Postman workspace, also attached an easier to read version)
https://www.postman.com/xapidevelopers/twitter-s-public-workspace/request/o1gumn2/get-tweets-usage
https://code.peren.gouv.fr/hackathon-2024/retrieval-modules/platform-docs-versions/-/blob/main/X_Twitter-API-V2/Usage.md

### CODE REVIEW

**Comment by jiahuijiang** [comment]
@PLhery I added an endpoint for usage/tweets, let me know what you think!

**Comment by jiahuijiang** [comment]
also tagging @alkihis :D

**Comment by PLhery** [comment]
Thank you!

**Comment by PLhery** [comment]
Published in 1.19.0

**Pull request merged**
