### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by deadcoder0904**
Thanks for this awesome library :)

### CODE REVIEW

**Review by PLhery — APPROVED** [review]
Thank you :)

**Comment by alkihis** [comment]
Hi, this was not a typo at all!
You can import **the default export** (ESModule way)
```ts
import TwitterApi from 'twitter-api-v2'
```
or you can import the `TwitterApi` variable from the package:
```ts
import { TwitterApi } from 'twitter-api-v2'
```

This is not the same thing! :)

**Comment by deadcoder0904** [comment]
@alkihis Oh I thought the `/` was misplaced.

I didn't knew it was `or`. I'll send another PR with a bunch of other typos I've found & replace this one with `or` instead of `/`

What do you think?

**Comment by alkihis** [comment]
Np! 
I'll fix it on my next PR, don't mind to do it.
If everything goes well, I should push a new feature soon!

**Comment by deadcoder0904** [comment]
I don't think it is `or` either, I'll just leave it as it is but yeah I still don't get it. I know about default export & named export but that `/` definitely felt like a typo :)

**Pull request merged**
