### PR TITLE
Added returnFullMediaData parameter to v1 uploadMedia

### PR DESCRIPTION
**Pull request by qedr**
Adding a returnFullMediaData parameter per: https://github.com/PLhery/node-twitter-api-v2/issues/506

### CODE REVIEW

**Comment by PLhery** [comment]
Hello, I'm sorry I didn't reply earlier, I was traveling for the holidays.

Awesome thank you, any reason why you also added this "prepare" script?

**Comment by qedr** [comment]
> Hello, I'm sorry I didn't reply earlier, I was traveling for the holidays.
> 
> Awesome thank you, any reason why you also added this "prepare" script?

Hi it's to ensure that the build script is executed by `npm install` so that the dist is always up to date.

**Comment by PLhery** [comment]
Sure, it could be handy but I think it depends on everyone's tastes and I'm not sure how it would affect the current github automated workflow (and caching mechanisms), so let's skip this change.

I'll remove it and merge the changes later tonight, thank you for proposing this CL!

**Comment by PLhery** [comment]
Thank you, feature available in v1.16.0 (I slightly added doc and better typings here https://github.com/PLhery/node-twitter-api-v2/commit/414ba71fb4bae6f3e9c0f746a21a0c11b868372e)

**Pull request merged**
