### PR TITLE
add timeout.

### PR DESCRIPTION
**Pull request by yassun4dev**
support timeout when client initialization.

### CODE REVIEW

**Comment by yayza** [comment]
> support timeout when client initialization.

Try adding this after initialization
```
function timeout(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
```
Then just use `await timeout(1000);`

**Comment by alkihis** [comment]
Hello, what do you want to do exactly?
Add a default timeout value for all requests?

**Comment by yassun4dev** [comment]
There was not enough explanation. Please let me know if there is a better way.

I don't want to specify a timeout in all situations.

I want to specify the timeout of Twitter API because to guarantee the worst execution time of AWS Lambda that performs a series of processing.

**Comment by yassun4dev** [comment]
Before AWS Lambda timeout itself, I'm necessary to handle the timeout error in each resource (DynamoDB, SQS, TwitterAPI, etc..).
In DynamoDB, I can set a timeout by AWS Client, but TwitterAPI is not currently.

I'm looking for a way for Lambda to notify me if the Twitter API doesn't respond correctly.

One idea is to set a timeout for the Twitter API client.

**Comment by alkihis** [comment]
I'm don't really sure this feature brings something to the library. 
Its global implementation don't really fit how the code is organized in the lib.

If you want a **specific** feature that apply only in your code, just fork the lib and use your fork.
However, I'm sure you can do what you want to do **without modifying the library code at all**, but enclosing call to methods that returns Promises into a global timeout-controlled Promise or async fn.

**Comment by yassun4dev** [comment]
I thought about your advice. And certainly, can set timeout by using async fn without this feature.

 Thanks!!

**Pull request closed without merging**
