### PR TITLE
add .quote method to v1ReadWrite

### PR DESCRIPTION
**Pull request by jonah-saltzman**
Adds a `quote` method to the `TwitterApiv1ReadWrite` class that takes the same parameters as `tweet`, in addition to `quoting_status_id: string`. Calls `v1.singleTweet` to get the username of the author of the quoted tweet, uses that to generate the appropriate QT url and appends the url to the status. Then calls `.tweet` as normal.

Passes all tests.

### CODE REVIEW

**Comment by alkihis** [comment]
Hi, thanks for your submission.

I identify a couple of problems here:
- You choose to get manually the tweet from API, fine, but what's happening on error? You should at least catch the error to re-throw a more meaningful message "you try to quote a tweet that is not accessible", f.e.
- You create an URL pushed to tweet content, but this is not required at all. `POST statuses/update` can take `attachment_url` parameter, that can be a tweet URL.
- A request is not needed at all :D A tweet URL from an ID can be constructed from scratch like: `https://twitter.com/i/statuses/<id>`, for example `https://twitter.com/i/statuses/1513249501238247430`.
- You add `.quote` to `.v1`, but `.v2`? A functionality should be implemented on both sides when possible.

**Comment by jonah-saltzman** [comment]
Thank you for the feedback! I will implement your suggestions. One question, if I construct the URL from scratch like you said with `https://twitter.com/i/`, should I still look up the tweet to make sure it exists? Or get rid of that call

**Comment by jonah-saltzman** [comment]
Actually, maybe the PR is unnecessary? I didn't know about `attachment_url`, which makes a .quote method somewhat redundant?

**Comment by alkihis** [comment]
If you want to use `attachment_url` you need to know how you can build the tweet URL :)
It can be nice to have a very simple method, like  ̀.reply`, that create the URL for you (without request) and bind it to `attachment_url`!

For `.v2`, you can create a similar method, but tweet ID is directly bound to `quote_tweet_id` parameter.

**Comment by jonah-saltzman** [comment]
Ok, let me know what you think :)

**Comment by jonah-saltzman** [comment]
Cool! My first OSS PR :)

**Pull request merged**
